
# This is the configuration for pre-commit, a local framework for managing pre-commit hooks
#   Check out the docs at: https://pre-commit.com/

default_stages: [pre-commit]
repos:
-   repo: https://github.com/hoxbro/clean_notebook
    rev: v0.1.17
    hooks:
      - id: clean-notebook
        args: [-i, slideshow, --keep-empty] # ignore RISE slideshow metadata and keep empty cells
