
# This is the configuration for pre-commit, a local framework for managing pre-commit hooks
#   Check out the docs at: https://pre-commit.com/

default_stages: [pre-commit]
repos:
-   repo: https://github.com/hoxbro/clean_notebook
    rev: v0.1.17
    hooks:
      - id: clean-notebook
        args: [-i, slideshow, --keep-empty] # ignore RISE slideshow metadata and keep empty cells
-   repo: local
    hooks:
      - id: run-pixi
        name: Run pixi
        entry: pixi
        language: system
        files: ^pixi\.toml$
        pass_filenames: false
        args: [workspace, export, conda-environment, --environment, default, binder/environment.yml]
-   repo: local
    hooks:
      - id: run-uv
        name: Run uv
        entry: uv
        language: system
        files: ^uv\.lock$
        pass_filenames: false
        args: [export, --format, requirements.txt, --no-dev, --output-file, binder/requirements.txt]
