[project]
name = "tutorial"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[environments]
docs = ["doc"]
tests = ["tests"]

[dependencies]
python = "=3.10"
datashader = ">=0.16.2"
holoviews = ">=1.19.1"
hvplot = ">=0.10.0"
panel = ">=1.4.4,<1.5.0"
param = ">=2.1.0,<3.0"
dask = "*"
jupyterlab = "*"
notebook = "*"
matplotlib-base = ">=3"
ipympl = "*"
fsspec = "*"
netcdf4 = "*"
plotly = "*"
pyarrow = "*"
xarray = "*"
# We don't want to download mkl packages (which are large) mainly seen on Windows
nomkl = "*"

[feature.doc]
channels = ["pyviz/label/tooling_dev", "conda-forge"]

[feature.doc.dependencies]
# Docs deps, that used to be in a `doc` environment but locking is so slow.
nbsite = ">=0.8.7"

[feature.doc.tasks]
docs-build  = 'sphinx-build -b html tutorial builtdocs'

[feature.tests.dependencies]
# Test deps, that used to be in a `test` env, same reasons.
pytest = "*"
nbsmoke = "*"

[feature.tests.tasks]
test-example = 'pytest tutorial --nbsmoke-run -k ".ipynb"'
