[project]
name = "tutorial"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[environments]
docs = ["doc"]
tests = ["tests"]

[tasks]
download-data = 'python tutorial/download_data.py'
launch-lab = { cmd = 'jupyter lab tutorial/index.ipynb', depends-on = ['download-data']}
launch-notebook = { cmd = 'jupyter notebook tutorial/index.ipynb', depends-on = ['download-data']}

[dependencies]
python = "=3.11"
datashader = ">=0.16.2"
holoviews = ">=1.19.1"
hvplot = ">=0.10.0"
panel = ">=1.4.4,<1.5.0"
param = ">=2.1.0,<3.0"
dask = "*"
jupyterlab = "*"
notebook = "*"
matplotlib-base = ">=3"
ipympl = "*"
fsspec = "*"
netcdf4 = "*"
plotly = "*"
pyarrow = "*"
xarray = "*"
# We don't want to download mkl packages (which are large) mainly seen on Windows
nomkl = "*"

[feature.doc]
channels = ["pyviz/label/tooling_dev", "conda-forge"]

[feature.doc.dependencies]
# Docs deps, that used to be in a `doc` environment but locking is so slow.
nbsite = ">=0.8.7"

[feature.doc.tasks]
docs-build = { cmd = 'sphinx-build -j auto -b html tutorial builtdocs', depends-on = ['download-data']}

[feature.tests.dependencies]
# Test deps, that used to be in a `test` env, same reasons.
pytest = "*"
pytest-xdist = "*"
nbval = "*"

[feature.tests.tasks]
test-example = { cmd = 'pytest tutorial -n logical --dist loadscope --nbval-lax -p no:python', depends-on = ['download-data']}
