name: build

on:
  push:
  workflow_dispatch:
    inputs:
      target:
        description: 'Tutorial version to publish'
        type: choice
        options:
        - dev
        - main
        required: true
        default: dev
  schedule:
    - cron: '0 2 1 */2 SUN'  # every two months on Sunday at 2 am

defaults:
  run:
    shell: bash -e {0}

jobs:
  publish_tutorial:
    name: Publish tutorial
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    steps:
      # Upload the tutorial
      - name: git clean
        run: git clean -fxd .
      - name: Create tutorial archive
        run: pixi run archive
      - name: save old
        run: cp holoviz_tutorial.zip holoviz_tutorial_${{ steps.vars.outputs.fdatetime }}.zip
      # - name: Upload tutorial
      #   if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
      #   run: aws s3 cp ./holoviz_tutorial_${{ steps.vars.outputs.fdatetime }}.zip s3://assets.holoviz.org/holoviz/tutorial/
      # - name: Upload tutorial
      #   if: |
      #     (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'main') ||
      #     (github.event_name == 'push' && steps.branch-name.outputs.branch == 'main')
      #   run: aws s3 cp ./holoviz_tutorial.zip s3://assets.holoviz.org/holoviz/tutorial/
