name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: '0 4 1 */2 SUN'  # every two months on Sunday at 4 am

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre_commit:
    name: Run pre-commit
    runs-on: 'ubuntu-latest'
    steps:
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          cache: false
      - uses: holoviz-dev/holoviz_tasks/pre-commit@v0
  test_suite:
    name: Pytest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    timeout-minutes: 30
    defaults:
      run:
        shell: bash -l {0} 
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          cache: false
      - name: pixi list
        run: pixi list
      - name: Example tests
        run: pixi run test-example
